### ISSUE TITLE
issue with importing lacosmicx

### ISSUE THREAD

**Issue by rcooke-ast** [Keck-DataReductionPipelines/KcwiDRP#6]
Hi there - I was running the standard pipeline command `reduce_kcwi -f KB*.fits.gz`, and I received an error that `_lacosmicx` is not defined. Looking at the `RemoveCosmicRays.py` file, it seems that `_lacosmicx` is imported in the `init` method, rather than at the top of the file. I do have `lacosmicx` installed, and it seems to be imported fine in the init method. I was able to fix the bug by moving the import to the top of the file (where the other imports are located).

Here is the full traceback:

```
2021-06-11 11:12:29:DRPF:ERROR: Exception name '_lacosmicx' is not defined while invoking RemoveCosmicRays
Traceback (most recent call last):
  File "/Users/rcooke/anaconda3/lib/python3.7/site-packages/keckdrpframework/core/framework.py", line 229, in execute
    action_output = pipeline.get_action(action_name)(action, context)
  File "/Users/rcooke/anaconda3/lib/python3.7/site-packages/keckdrpframework/pipelines/base_pipeline.py", line 84, in f
    return obj.apply()
  File "/Users/rcooke/anaconda3/lib/python3.7/site-packages/keckdrpframework/primitives/base_primitive.py", line 57, in apply
    self.output = self._perform()
  File "/Users/rcooke/anaconda3/lib/python3.7/site-packages/kcwidrp/primitives/RemoveCosmicRays.py", line 54, in _perform
    mask, clean = _lacosmicx.lacosmicx(
NameError: name '_lacosmicx' is not defined
```

**Comment by rcooke-ast** [comment]
Sorry - I meant to post this in the python DRP
